<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Cla',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Clases',
  'published_date' => '2017-05-26 11:45:06',
  'type' => 'module',
  'version' => 1495799106,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Clases',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Cla_Clases',
      'class' => 'Cla_Clases',
      'path' => 'modules/Cla_Clases/Cla_Clases.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/cla_clases_activities_calls_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cla_clases_activities_callsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cla_clases_activities_meetingsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cla_clases_activities_notesMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cla_clases_activities_tasksMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cla_clases_activities_emailsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Cla_Clases',
      'to' => 'modules/Cla_Clases',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cla_Clases.php',
      'to_module' => 'Cla_Clases',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_calls_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_meetings_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_notes_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_tasks_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cla_clases_activities_emails_Cla_Clases.php',
      'to_module' => 'Cla_Clases',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'cla_clases_activities_calls_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'cla_clases_activities_meetings_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'cla_clases_activities_notes_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'cla_clases_activities_tasks_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);